# Generated by Django 3.0.4 on 2020-04-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('questions', models.CharField(max_length=550)),
                ('details', models.TextField(max_length=500)),
                ('category', models.CharField(max_length=100)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
