# Generated by Django 3.0.4 on 2020-04-09 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='questions',
            new_name='qsn',
        ),
    ]
