# Generated by Django 3.0.4 on 2020-04-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200409_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='timeStamp',
            field=models.DateTimeField(blank=True),
        ),
    ]
