# Generated by Django 3.0.4 on 2020-04-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200409_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('qsn', models.CharField(max_length=550)),
                ('details', models.TextField(max_length=500)),
                ('category', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=150)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
