# Generated by Django 3.0.4 on 2020-04-10 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200410_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ask',
            old_name='qsn',
            new_name='ask',
        ),
    ]
