# Generated by Django 3.0.4 on 2020-04-10 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200410_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ask',
            old_name='ask',
            new_name='askq',
        ),
    ]
