# Generated by Django 3.0.4 on 2020-04-10 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200410_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ask',
            old_name='qsns',
            new_name='askq',
        ),
    ]
