# Generated by Django 3.0.4 on 2020-04-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200410_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='ask',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
