# Generated by Django 3.0.4 on 2020-04-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_ask_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='ask',
            name='author',
            field=models.CharField(default='none', max_length=13),
            preserve_default=False,
        ),
    ]
