# Generated by Django 3.0.4 on 2020-04-13 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_ask_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ask',
            name='author',
        ),
    ]
