# Generated by Django 3.0.4 on 2020-04-19 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20200419_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ask',
            options={'ordering': ('-updated',)},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='date_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='message',
        ),
    ]
