# Generated by Django 3.0.4 on 2020-04-19 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20200419_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ask',
            options={},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default='01', max_length=160),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='timeStamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
