# Generated by Django 3.0.4 on 2020-04-19 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20200419_1943'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
